# Generated by Django 4.2.4 on 2023-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user_student_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='loginuser',
            field=models.CharField(default='prashant rathour default', max_length=100, unique=True),
        ),
    ]
