# Generated by Django 4.2.4 on 2023-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_user_student_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='loginuser',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
