# Generated by Django 4.2.4 on 2023-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='userID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
