# Generated by Django 4.2.4 on 2023-09-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='loginuser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='userID',
        ),
    ]
