# Generated by Django 4.2.4 on 2023-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_loginuser_remove_student_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='loginuser',
            field=models.CharField(default='xrz', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='userID',
            field=models.CharField(default='12322', max_length=100, unique=True),
        ),
    ]
