# Generated by Django 4.2.4 on 2023-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githublink', models.URLField()),
                ('deployelink', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='red', max_length=10)),
            ],
        ),
    ]
