# Generated by Django 4.2.4 on 2023-09-06 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignmentsubmission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deployelink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='githublink',
            field=models.URLField(default=datetime.datetime(2023, 9, 6, 14, 20, 18, 270482, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='showSubmissionForm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 6, 14, 21, 12, 924538, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
