# Generated by Django 4.2.4 on 2023-09-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_deployelink_assignment_githublink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='githublink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
