# Generated by Django 4.2.4 on 2023-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='instructors',
            field=models.ManyToManyField(related_name='departments', to='instructors.instructor'),
        ),
    ]
