# Generated by Django 4.2.4 on 2023-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('courses', '0002_initial'),
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='instructors',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments', to='instructors.instructor'),
        ),
    ]
