# Generated by Django 4.2.4 on 2023-09-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_instructor_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
